development:
  adapter: postgresql
  encoding: unicode
  database: gity_development
  pool: 5
  host: localhost
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gity_test
  pool: 5
  host: localhost
  timeout: 5000
  username:
  password:
